export const ContactsIndicator = {
  contactsOnWhatsapp: "CONTACTS ON WHATSAPP",
  ChatRoomDividerLabels: [
    { key: "A", label: "A" },
    { key: "B", label: "B" },
    { key: "C", label: "C" },
    { key: "D", label: "D" },
    { key: "E", label: "E" },
    { key: "F", label: "F" },
    { key: "G", label: "G" },
    { key: "H", label: "H" },
    { key: "I", label: "I" },
    { key: "J", label: "J" },
    { key: "K", label: "K" },
    { key: "L", label: "L" },
    { key: "M", label: "M" },
    { key: "N", label: "N" },
    { key: "O", label: "O" },
    { key: "P", label: "P" },
    { key: "Q", label: "Q" },
    { key: "R", label: "R" },
    { key: "S", label: "S" },
    { key: "T", label: "T" },
    { key: "U", label: "U" },
    { key: "V", label: "V" },
    { key: "W", label: "W" },
    { key: "X", label: "X" },
    { key: "Y", label: "Y" },
    { key: "Z", label: "Z" },
  ],
};
